# Generated by Django 4.2.6 on 2023-10-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmenu',
            name='font_awesome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
